[17-Jul-24 18:41:35 - INFO] - HuTao.modules.<module> - [INFO]: IMPORTING PLUGINS
[17-Jul-24 18:41:38 - INFO] - __main__.<module> - Traceback (most recent call last):
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/__main__.py", line 53, in <module>
    loop.run_until_complete(start_bot())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/__main__.py", line 25, in start_bot
    imported_module = importlib.import_module(f"HuTao.modules.{module}")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/modules/admins.py", line 16, in <module>
    from HuTao.helpers.extraction import extract_user
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/helpers/extraction.py", line 8, in <module>
    from HuTao.database.users_db import *
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/database/__init__.py", line 4, in <module>
    from async_pymongo import AsyncClient
ModuleNotFoundError: No module named 'async_pymongo'

[17-Jul-24 18:41:38 - INFO] - __main__.<module> - ------------------------ Stopped Services ------------------------
[17-Jul-24 18:49:18 - INFO] - HuTao.modules.<module> - [INFO]: IMPORTING PLUGINS
[17-Jul-24 18:49:18 - INFO] - __main__.<module> - Traceback (most recent call last):
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/__main__.py", line 53, in <module>
    loop.run_until_complete(start_bot())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/__main__.py", line 25, in start_bot
    imported_module = importlib.import_module(f"HuTao.modules.{module}")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/modules/admins.py", line 16, in <module>
    from HuTao.helpers.extraction import extract_user
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/helpers/extraction.py", line 8, in <module>
    from HuTao.database.users_db import *
  File "/home/senpaiii/Code/REPOS/Hu-Tao-main/HuTao/database/__init__.py", line 4, in <module>
    from async_pymongo import AsyncClient
ModuleNotFoundError: No module named 'async_pymongo'

[17-Jul-24 18:49:18 - INFO] - __main__.<module> - ------------------------ Stopped Services ------------------------
